#ifndef STATE_MACHINE_ENUM
#define STATE_MACHINE_ENUM

enum StateMachineEnum {
	SIGNAL_DRAW = 1,
	SIGNAL_DRAW_MENU_HANDLE = 2,
	SIGNAL_SCALE = 3,
	CHECK_TOUCH = 4,
	MAIN_MENU = 5,
	SNAPSHOT = 6,
	SCALE_MENU = 7,
	DRAW_MENU = 8,
	WAIT_FOR_TOUCH = 9
};

#endif // !STATE_MACHINE_ENUM

